-- CreateTable
CREATE TABLE `foods` (
    `food_id` INTEGER NOT NULL,
    `food_name` VARCHAR(191) NOT NULL,
    `meal_type` VARCHAR(191) NOT NULL,
    `diet_type` VARCHAR(191) NOT NULL,
    `calories_kcal` DOUBLE NOT NULL,
    `carbohydrates_g` DOUBLE NOT NULL,
    `protein_g` DOUBLE NOT NULL,
    `fat_g` DOUBLE NOT NULL,
    `fiber_g` DOUBLE NOT NULL,
    `calcium_mg` DOUBLE NOT NULL,
    `magnesium_mg` DOUBLE NOT NULL,
    `iron_mg` DOUBLE NOT NULL,
    `zinc_mg` DOUBLE NOT NULL,
    `vitamin_A` DOUBLE NOT NULL,
    `vitamin_B1` DOUBLE NOT NULL,
    `vitamin_B2` DOUBLE NOT NULL,
    `vitamin_B12` DOUBLE NOT NULL,
    `vitamin_C` DOUBLE NOT NULL,
    `vitamin_D` DOUBLE NOT NULL,
    `vitamin_E` DOUBLE NOT NULL,
    `vitamin_K` DOUBLE NOT NULL,
    `vitamin_H` DOUBLE NOT NULL,
    `food_category` VARCHAR(191) NOT NULL,
    `seasonal` VARCHAR(191) NOT NULL,
    `season` VARCHAR(191) NOT NULL,
    `ingredients` VARCHAR(191) NOT NULL,
    `region` VARCHAR(191) NOT NULL,
    `state` VARCHAR(191) NOT NULL,
    `source` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`food_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
